apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bug-tracker.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bug-tracker.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ include "bug-tracker.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "bug-tracker.fullname" . }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      serviceAccountName: {{ include "bug-tracker.fullname" . }}-sa
      containers:
        - name: bug-tracker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 5000
              name: http
          envFrom:
            - configMapRef:
                name: {{ include "bug-tracker.fullname" . }}-config
            - secretRef:
                name: {{ include "bug-tracker.fullname" . }}-secret
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "bug-tracker.fullname" . }}-secret
                  key: DATABASE_URL
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path | quote }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            failureThreshold: 5
          volumeMounts:
            - name: uploads
              mountPath: {{ .Values.env.UPLOAD_FOLDER }}
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      volumes:
        - name: uploads
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "bug-tracker.fullname" . }}-pvc
          {{- else }}
          emptyDir: {}
          {{- end }}
