apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bug-tracker.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bug-tracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.secret.SECRET_KEY | quote }}
  DATABASE_URL: {{ .Values.secret.DATABASE_URL | quote }}
