name: Changelog CI

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get latest release version
        id: latest_release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(gh release view --json tagName --jq '.tagName')
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.2.0
        with:
          config_file: .github/changelog-ci-config.yaml
          github_token: ${{ secrets.GITHUB_TOKEN }}